  version: '3'
    
  services:
    db:
      image: postgres
      environment:
        - POSTGRES_DB=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
      volumes:
        - db-data:/var/lib/postgresql/data
    dbadmin:
            image: dockage/phppgadmin:latest
            ports:
              - "90:80"
            environment:
              - PHP_PG_ADMIN_SERVER_HOST=db
    web:
      build: .
      command: python manage.py runserver 0.0.0.0:8000
      volumes:
        - .:/code
      ports:
        - "9000:8000"
      depends_on:
        - db
  volumes:
    db-data: