# Generated by Django 2.2.12 on 2020-05-12 16:01

from django.db import migrations, models
import utils.id_generator


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.CharField(default=utils.id_generator.id_gen, editable=False, max_length=9, primary_key=True, serialize=False)),
                ('request', models.CharField(default='', max_length=4000)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestReport',
            fields=[
                ('id', models.CharField(default=utils.id_generator.id_gen, editable=False, max_length=9, primary_key=True, serialize=False)),
                ('report_id', models.IntegerField()),
                ('temperature', models.DecimalField(decimal_places=30, default=0, max_digits=100)),
                ('duration', models.CharField(default='', max_length=1000)),
                ('timestamp', models.DateField()),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UploadedFiles',
            fields=[
                ('uploaded_at', models.DateField(auto_created=True)),
                ('id', models.CharField(default=utils.id_generator.id_gen, editable=False, max_length=9, primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=400)),
            ],
        ),
    ]
