# Generated by Django 2.2.12 on 2020-05-12 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csvapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testreport',
            name='timestamp',
            field=models.CharField(default='', max_length=60),
        ),
    ]
